#!/usr/bin/env bash
# DEP-02: one-command install of commit-agent + commit-agent-once on a Godot target host.
#
# Usage:
#   sudo bash packages/commit-agent/scripts/install.sh
#   COMMIT_AGENT_BIN=/opt/pgos/bin/commit-agent sudo -E bash packages/commit-agent/scripts/install.sh
#
# Env:
#   COMMIT_AGENT_BIN   Install path for the binary (default: /usr/local/bin/commit-agent)
#   COMMIT_AGENT_ONCE  Install path for ForcedCommand wrapper (default: same dir as binary + -once)
#   SKIP_BUILD=1       Skip go build (copy existing bin/commit-agent if present)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMMIT_AGENT_BIN="${COMMIT_AGENT_BIN:-/usr/local/bin/commit-agent}"
ONCE_DEFAULT="$(dirname "${COMMIT_AGENT_BIN}")/commit-agent-once"
COMMIT_AGENT_ONCE="${COMMIT_AGENT_ONCE:-${ONCE_DEFAULT}}"

echo "pgos commit-agent install (DEP-02)"
echo "  binary: ${COMMIT_AGENT_BIN}"
echo "  once:   ${COMMIT_AGENT_ONCE}"

BIN_DIR="$(dirname "${COMMIT_AGENT_BIN}")"
ONCE_DIR="$(dirname "${COMMIT_AGENT_ONCE}")"
mkdir -p "${BIN_DIR}" "${ONCE_DIR}"

BUILD_OUT="${PKG_ROOT}/bin/commit-agent"
if [[ "${SKIP_BUILD:-0}" != "1" ]]; then
  if ! command -v go >/dev/null 2>&1; then
    echo "ERROR: go toolchain required (or set SKIP_BUILD=1 with a prebuilt binary)" >&2
    exit 1
  fi
  mkdir -p "${PKG_ROOT}/bin"
  echo "Building ./cmd/agent → ${BUILD_OUT}"
  (cd "${PKG_ROOT}" && go build -o "${BUILD_OUT}" ./cmd/agent)
elif [[ ! -f "${BUILD_OUT}" ]]; then
  echo "ERROR: SKIP_BUILD=1 but ${BUILD_OUT} missing" >&2
  exit 1
fi

install -m 0755 "${BUILD_OUT}" "${COMMIT_AGENT_BIN}"

# Wrapper respects COMMIT_AGENT_BIN at runtime (ForcedCommand environment can set it).
cat >"${COMMIT_AGENT_ONCE}" <<EOF
#!/usr/bin/env bash
# Generated by packages/commit-agent/scripts/install.sh (DEP-02)
set -euo pipefail
exec "\${COMMIT_AGENT_BIN:-${COMMIT_AGENT_BIN}}" -once "\${SSH_ORIGINAL_COMMAND:-\$*}"
EOF
chmod 0755 "${COMMIT_AGENT_ONCE}"

# H-02: share tscn-merge.mjs for operators/debug (merge-apply verb is pure Go in the agent).
SHARE_DIR="${PGOS_SHARE_DIR:-/usr/share/pgos}"
TSCN_MERGE_SRC="${PKG_ROOT}/../../workers/scripts/lib/tscn-merge.mjs"
if [[ -f "${TSCN_MERGE_SRC}" ]]; then
  mkdir -p "${SHARE_DIR}"
  install -m 0644 "${TSCN_MERGE_SRC}" "${SHARE_DIR}/tscn-merge.mjs"
  echo "  share:  ${SHARE_DIR}/tscn-merge.mjs"
elif [[ -f "${PKG_ROOT}/share/tscn-merge.mjs" ]]; then
  mkdir -p "${SHARE_DIR}"
  install -m 0644 "${PKG_ROOT}/share/tscn-merge.mjs" "${SHARE_DIR}/tscn-merge.mjs"
  echo "  share:  ${SHARE_DIR}/tscn-merge.mjs"
else
  echo "WARN: tscn-merge.mjs not found (optional share install skipped)" >&2
fi

# Optional systemd unit if present
if [[ -f "${PKG_ROOT}/systemd/pgos-commit-agent.service" ]]; then
  echo "systemd unit available at ${PKG_ROOT}/systemd/pgos-commit-agent.service (install manually if needed)"
fi

echo "Installed:"
echo "  ${COMMIT_AGENT_BIN}"
echo "  ${COMMIT_AGENT_ONCE}"
echo "Verify: ${COMMIT_AGENT_BIN} -once 'stat-lock /var/godot/projects'"
echo "        ${COMMIT_AGENT_BIN} -once 'merge-apply /var/godot/projects/game scenes/player.tscn' < patch.json"
