-- Enforce valid job status values at the database layer
ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_status_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_status_check CHECK (
  status IN (
    'QUEUED', 'DISPATCHING', 'DISPATCH_TIMEOUT', 'BLOCKED', 'STAGING',
    'VALIDATING', 'VALIDATION_REPORT', 'VALIDATION_FAILED', 'REIMPORT_FAILED',
    'COMMITTING', 'COMMIT_FAILED', 'POST_COMMIT_VERIFY', 'ROLLBACK',
    'COMPLETED', 'LOCK_STALE', 'DEP_FAILED', 'PAUSED_EDITOR_LOCK',
    'CANCELLED', 'DEAD_LETTER'
  )
);